-- 0033_events.sql — unified, append-only activity log behind the instance-admin
-- Events screen. One row per noteworthy thing that happens: logins (incl. failed),
-- page views/edits, access/admin changes, asks, and API-key requests.
--
-- Why a separate table when access_audit / api_key_audit / ask_log already exist:
-- those stay the canonical, specialised trails (and access_audit is kept forever
-- for compliance). `events` is the *unified feed* — one indexed table the admin
-- screen reads with keyset pagination + filters, fed by recordEvent() at each
-- chokepoint. High-volume types (page.view, api.request) are bounded by a
-- retention GC (events_gc.go, TELA_EVENTS_RETENTION_DAYS, default 180d).
--
-- actor_label / target_label are denormalised at write time so the feed renders
-- without joins and survives user/page deletion (and names the attempted identity
-- on a failed login, where no user row exists). actor_user_id is NULL for
-- anonymous/system/failed-login rows.

CREATE TABLE events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type          TEXT NOT NULL,                                  -- 'auth.login','auth.login_failed','auth.logout','page.view','page.create','page.edit','access.<action>','ask','api.request'
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, -- NULL = anonymous / system / failed login
  actor_label   TEXT NOT NULL DEFAULT '',                       -- username/email/identifier at event time
  target_kind   TEXT NOT NULL DEFAULT '',                       -- 'page','space','org','user','api_key',…
  target_id     BIGINT,
  target_label  TEXT NOT NULL DEFAULT '',                       -- page title / space name / etc. for display
  detail        TEXT NOT NULL DEFAULT '',                       -- short human detail (source, identifier, method+path+status, …)
  ip            TEXT NOT NULL DEFAULT '',
  user_agent    TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT tela_now()
);

-- Keyset pagination (ORDER BY id DESC, WHERE id < cursor) + the two common filters.
CREATE INDEX idx_events_id ON events(id DESC);
CREATE INDEX idx_events_type_id ON events(type, id DESC);
CREATE INDEX idx_events_actor_id ON events(actor_user_id, id DESC);
CREATE INDEX idx_events_created ON events(created_at);
