-- 0044_ai_usage.sql — per-call AI usage log for cost estimation.
--
-- Until now AI usage was only a per-month call COUNTER (cloud_usage.llm_calls)
-- for plan caps — useless for cost, which is driven by TOKENS. This logs one row
-- per AI call (chat completion, embedding, image gen) with token counts, so
-- total + per-week + per-model usage is a simple aggregation, and applying a
-- per-provider price table later estimates spend.
--
-- Token counts are ESTIMATES (≈ chars/4) recorded at the service chokepoints —
-- good enough for budgeting, not invoicing. `units` carries non-token counts
-- (e.g. # images). Best-effort writes: a failed insert never fails the AI call.
CREATE TABLE ai_usage (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TEXT   NOT NULL DEFAULT tela_now(),
  kind          TEXT   NOT NULL,            -- 'chat' | 'embed' | 'image'
  model         TEXT   NOT NULL DEFAULT '',
  input_tokens  BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  units         BIGINT NOT NULL DEFAULT 0   -- non-token count (e.g. images); 0 for chat/embed
);

CREATE INDEX idx_ai_usage_created ON ai_usage(created_at);
CREATE INDEX idx_ai_usage_kind_created ON ai_usage(kind, created_at);
